title: "Arawi Aura"
description: "Una colección bilingüe de poesía contemporánea"
baseurl: ""
url: "https://benitoanagua.github.io"

author:
  name: "Benito Anagua"
  email: "contact@arawiaura.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
timezone: America/Lima

sass:
  style: compressed
  sass_dir: _sass
  load_paths:
    - _sass

# Collections
collections:
  poems_en:
    output: true
    permalink: /en/poems/:slug/
  poems_es:
    output: true
    permalink: /es/poemas/:slug/

# Defaults
defaults:
  - scope:
      path: ""
      type: "poems_en"
    values:
      layout: "post"
      lang: "en"
  - scope:
      path: ""
      type: "poems_es"
    values:
      layout: "post"
      lang: "es"

languages: ["en", "es"]
default_lang: "es"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
